spring:
    application:
        name: "Food Delivery Api"
    data:
      mongodb:
          uri: mongodb+srv://admin:admin@cluster0.uklns4x.mongodb.net/food-delivery?retryWrites=true&w=majority&appName=Cluster0

